[package]
name = "postlice"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { path = "iced" }
iced_test = { path = "iced/test" }
serde = { version = "1.0.226", features = [ "derive" ] }
serde_json = "1.0.145"
