[package]
name = "postlice"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { path = "iced" }
iced_test = { path = "iced/test" }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
sqlx = { version = "0.8.6", features = [ "runtime-tokio", "sqlite" ] }
